%YAML:1.0
% Nao se esqueca que ao realizar qualquer adicao ou remocao neste arquivo, eh necessario adaptar a enumeracao 'Cores' em camera.hpp e na funcao inicializaMapa em camera.cpp
---
AreaCampo:
  X: 84
  Y: 32
  Largura: 556
  Altura: 425

BuscaROIFrameAnterior:
  Area: 90
  numeroTentativasBuscaROI: 3
  proporcaoAumentoAmplitudeROI: 5

BuscaCampoTodo:
  numeroTentativasBuscaCampoTodo: 3
  proporcaoAumentoAmplitudeCampoTodo: 5

Cores:
  - AMARELO:
      H_MIN: 27
      H_MAX: 33
      S_MIN: 57
      S_MAX: 116
      V_MIN: 246
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 3
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - AZUL:
      H_MIN: 59
      H_MAX: 137
      S_MIN: 173
      S_MAX: 255
      V_MIN: 147
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 3
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ALARANJADO:
      H_MIN: 4
      H_MAX: 12
      S_MIN: 139
      S_MAX: 195
      V_MIN: 192
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ROSA:
      H_MIN: 150
      H_MAX: 158
      S_MIN: 32
      S_MAX: 50
      V_MIN: 252
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ROXO:
      H_MIN: 124
      H_MAX: 132
      S_MIN: 49
      S_MAX: 64
      V_MIN: 243
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - VERDE:
      H_MIN: 33
      H_MAX: 39
      S_MIN: 68
      S_MAX: 154
      V_MIN: 239
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6
