%YAML:1.0
% Nao se esqueca que ao realizar qualquer adicao ou remocao neste arquivo, eh necessario adaptar a enumeracao 'Cores' em camera.hpp e na funcao inicializaMapa em camera.cpp
%AreaCampo:
%  isLadoEsquerdo: indica se estamos do lado esquerdo do campo (= 1) ou se estamos do lado direito (= 0)
%EscalaConversao:
% TamanhoEmPixelsObjeto: tamanho em pixels do objeto utilizado como base.
% TamanhoEmCentimetrosObjeto: tamanho do mesmo objeto mas em centimetros.
---
AreaCampo:
  X: 2
  Y: 2
  Largura: 636
  Altura: 477
  isLadoEsquerdo: 1

EscalaConversao:
  TamanhoEmPixelsObjeto: 548
  TamanhoEmCentimetrosObjeto: 170

BuscaROIFrameAnterior:
  Area: 90
  numeroTentativasBuscaROI: 3
  proporcaoAumentoAmplitudeROI: 5

BuscaCampoTodo:
  numeroTentativasBuscaCampoTodo: 3
  proporcaoAumentoAmplitudeCampoTodo: 5

Cores:
  - AMARELO:
      H_MIN: 27
      H_MAX: 31
      S_MIN: 97
      S_MAX: 147
      V_MIN: 192
      V_MAX: 233
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 3
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - AZUL:
      H_MIN: 113
      H_MAX: 118
      S_MIN: 88
      S_MAX: 129
      V_MIN: 155
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 3
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ALARANJADO:
      H_MIN: 5
      H_MAX: 10
      S_MIN: 138
      S_MAX: 179
      V_MIN: 255
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ROSA:
      H_MIN: 150
      H_MAX: 159
      S_MIN: 62
      S_MAX: 103
      V_MIN: 219
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ROXO:
      H_MIN: 118
      H_MAX: 129
      S_MIN: 41
      S_MAX: 75
      V_MIN: 180
      V_MAX: 226
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - VERDE:
      H_MIN: 40
      H_MAX: 45
      S_MIN: 95
      S_MAX: 139
      V_MIN: 180
      V_MAX: 239
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 2
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 2
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6
