%YAML:1.0
% Nao se esqueca que ao realizar qualquer adicao ou remocao neste arquivo, eh necessario adaptar a enumeracao 'Cores' em camera.hpp e na funcao inicializaMapa em camera.cpp
%AreaCampo:
%  isLadoEsquerdo: indica se estamos do lado esquerdo do campo (= 1) ou se estamos do lado direito (= 0)
%EscalaConversao:
% TamanhoEmPixelsObjeto: tamanho em pixels do objeto utilizado como base.
% TamanhoEmCentimetrosObjeto: tamanho do mesmo objeto mas em centimetros.
---
AreaCampo:
  X: 17
  Y: 14
  Largura: 616
  Altura: 464
  isLadoEsquerdo: 0

EscalaConversao:
  TamanhoEmPixelsObjeto: 616
  TamanhoEmCentimetrosObjeto: 170

BuscaROIFrameAnterior:
  Area: 90
  numeroTentativasBuscaROI: 3
  proporcaoAumentoAmplitudeROI: 5

BuscaCampoTodo:
  numeroTentativasBuscaCampoTodo: 3
  proporcaoAumentoAmplitudeCampoTodo: 5

Cores:
  - AMARELO:
      H_MIN: 29
      H_MAX: 32
      S_MIN: 150
      S_MAX: 213
      V_MIN: 227
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 3
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - AZUL:
      H_MIN: 108
      H_MAX: 115
      S_MIN: 94
      S_MAX: 121
      V_MIN: 211
      V_MAX: 255
      AreaMinima: 30
      AreaMaxima: 700
      NumObjetosCor: 3
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ALARANJADO:
      H_MIN: 6
      H_MAX: 15
      S_MIN: 149
      S_MAX: 198
      V_MIN: 237
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 900
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ROSA:
      H_MIN: 165
      H_MAX: 170
      S_MIN: 115
      S_MAX: 137
      V_MIN: 218
      V_MAX: 248
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ROXO:
      H_MIN: 121
      H_MAX: 129
      S_MIN: 55
      S_MAX: 85
      V_MIN: 200
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - VERDE:
      H_MIN: 39
      H_MAX: 73
      S_MIN: 77
      S_MAX: 163
      V_MIN: 219
      V_MAX: 247
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6
