%YAML:1.0
% Nao se esqueca que ao realizar qualquer adicao ou remocao neste arquivo, eh necessario adaptar a enumeracao 'Cores' em camera.hpp e na funcao inicializaMapa em camera.cpp
---
AreaCampo:
  X: 94
  Y: 36
  Largura: 544
  Altura: 422

EscalaConversao:
  TamanhoEmPixelsObjeto: 60
  TamanhoEmCentimetrosObjeto: 10

BuscaROIFrameAnterior:
  Area: 90
  numeroTentativasBuscaROI: 3
  proporcaoAumentoAmplitudeROI: 5

BuscaCampoTodo:
  numeroTentativasBuscaCampoTodo: 3
  proporcaoAumentoAmplitudeCampoTodo: 5

Cores:
  - AMARELO:
      H_MIN: 28
      H_MAX: 35
      S_MIN: 63
      S_MAX: 172
      V_MIN: 196
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 3
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - AZUL:
      H_MIN: 100
      H_MAX: 107
      S_MIN: 89
      S_MAX: 115
      V_MIN: 240
      V_MAX: 255
      AreaMinima: 30
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ALARANJADO:
      H_MIN: 4
      H_MAX: 15
      S_MIN: 87
      S_MAX: 194
      V_MIN: 184
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 900
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ROSA:
      H_MIN: 151
      H_MAX: 161
      S_MIN: 34
      S_MAX: 83
      V_MIN: 185
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - ROXO:
      H_MIN: 122
      H_MAX: 127
      S_MIN: 60
      S_MAX: 86
      V_MIN: 214
      V_MAX: 255
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6

  - VERDE:
      H_MIN: 37
      H_MAX: 44
      S_MIN: 92
      S_MAX: 144
      V_MIN: 206
      V_MAX: 251
      AreaMinima: 100
      AreaMaxima: 700
      NumObjetosCor: 1
      VezesErode: 3
      LarguraRetanguloErode: 3
      AlturaRetanguloErode: 3
      VezesDilatate: 3
      LarguraRetanguloDilatate: 6
      AlturaRetanguloDilatate: 6
